package nyu.cs.pqs.ps5.listener;

import nyu.cs.pqs.ps5.grid.GridColor;

/***
 * This interface provides all the events that a view can get informed about 
 * from a model.
 * @author Anurag
 *
 */
public interface Connect4Listener {
  /***
   * This event is generated by model when the game is to be started. As a view, 
   * necessary information should be displayed for user.
   */
  public void gameStart();
  
  /***
   * This event is generated by model when the game is drawn.As a view, 
   * necessary information should be displayed for user.
   */
  public void gameDraw();
  
  /***
   * This event is genrated by model when the game is drawn. As a view, 
   * necessary information should be displayed for user. 
   */
  public void gameEnd();
  
  /***
   * This event is generated by model when the user has clicked on a column that
   * has already filled all its slots. As a view, 
   * necessary information should be displayed for user.
   */
  public void invalidMove();
  
  /***
   * This event is generated by model when a player has won. As a view, 
   * necessary information should be displayed for user.
   */
  public void playerWon(GridColor color);
  
  /***
   * This event is generated by model when the user has clicked on a column and coin is to be
   * added in that column. As a view, 
   * necessary information should be displayed for user.
   */
  public void coinAdded(int row, int column, GridColor color);
}
